### ISSUE TITLE
Emacs trunk issues

### ISSUE THREAD

**Issue by rejeep** [cask/servant#11]
With a hosted Servant server, this will fail on Emacs trunk:

``` lisp
(progn
  (require 'package)
  (add-to-list 'package-archives 
           '("localhost" .
         "http://127.0.0.1:9191/packages/"))
  (package-initialize)
  (package-refresh-contents))
```

**Comment by swsnr** [comment]
@rejeep How can I make elnode print the accessed URLs to standard output?

**Comment by rejeep** [comment]
I'm definitely not an elnode expert. I just `print` a message in the handlers when I want to figure that out. You might also be able to get some info out from `httpcon` in `servant--root-handler`.

**Comment by swsnr** [comment]
I think I found the culprit.  package.el in trunk tries to fetch signature files from package archives.  It implicitly relies on the HTTP response code to determine whether an archive has signatures at all.

Since servant.el defaults to returning 200, package.el thinks it has a signature file for the local archive, while it actually just got an empty file.  Depending on whether gpg is installed, you now either get an error about a missing gpg executable, or an invalid signature file.

**Comment by swsnr** [comment]
@rejeep Well, this is indeed the issue.  When returning 404 from the default handler, everything works well.

While I am at it, why don't you just serve the whole `servant/` directory via the built-in elnode webserver?  That would  give you HTTP response codes, headers, mimetype handling, index pages, and caching for free, and is just a single line.  The only drawback is that we expose the `tmp/` directory as well, but we could just put `servant.pid` into a different place.

**Comment by swsnr** [comment]
Besides, we could also generate the index on the file, if the `index` file is absent.

**Comment by rejeep** [comment]
We could have this directory structure:

```
- servant
 - public
  - packages
   - archive-contents
   - foo-1.2.3.el
   - bar-3.2.1.tar
 - tmp
  - servant.pid
```

Then we could simply serve the `public` directory as you say.

**Comment by swsnr** [comment]
@rejeep Mind to continue the discussion at #12?

**Comment by rejeep** [comment]
Let's!
